### ISSUE TITLE
Roadmap of integration plan

### ISSUE THREAD

**Issue by yzh119** [dglai/FeatGraph#2]
- [x] Fix the dlpack bug: we found that we'll meet segfault irregularly when integrating featgraph to DGL.
  - TODO(zihao): find a minimal example to reproduce the error.
- [x] Support broadcasting
  - TODO(zihao): investigate how to support general broadcasting.
- [x] SPMM with edge weight
- [x] Process node/edge mapping on DGL end before feeding the tensors to featgraph.
